/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2022-05-05 10:14:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1650964475785L));
    _jspx_dependants.put("jar:file:/home/pradip/Desktop/Spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/springmvc/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"utf-8\">\r\n");
      out.write("	<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("	<title>Login Page</title>\r\n");
      out.write("	<link href='");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("' type=\"text/css\" rel=\"stylesheet\" />\r\n");
      out.write("	<link rel=\"stylesheet\" href='");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("'>\r\n");
      out.write("	<script type=\"text/javascript\" src='");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("' ></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	\r\n");
      out.write("	<!-- Main section for other content -->\r\n");
      out.write("	<main>\r\n");
      out.write("		<div class=\"container\">	\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-md-2\"></div>\r\n");
      out.write("				<div class=\"col-md-8 col-sm-12\">\r\n");
      out.write("					<section class=\"form-section\">\r\n");
      out.write("						<form id=\"login-form\" action=\"processlogin\" method=\"post\">\r\n");
      out.write("							<!-- Below div for form heading -->\r\n");
      out.write("							<div class=\"form-heading\">\r\n");
      out.write("								<h2>Login Page</h2>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<!-- Below div for email of user -->\r\n");
      out.write("							<div class=\"form-group1\">\r\n");
      out.write("								<label for=\"\">Email :</label> <input type=\"email\"\r\n");
      out.write("									class=\"form-control\" id=\"email\" name=\"email\"\r\n");
      out.write("									placeholder=\"Please enter valid email\">\r\n");
      out.write("								<p class=\"field-error\" id=\"email-error\"></p>\r\n");
      out.write("\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<!-- Below div for password of user -->\r\n");
      out.write("							<div class=\"form-group1\">\r\n");
      out.write("								<label for=\"password\">Password :</label> <input type=\"password\"\r\n");
      out.write("									class=\"form-control\" id=\"password\" name=\"password\"\r\n");
      out.write("									placeholder=\"Please enter Password\">\r\n");
      out.write("								<p class=\"field-error\" id=\"password-error\"></p>\r\n");
      out.write("							</div>\r\n");
      out.write("							\r\n");
      out.write("							<div class=\"form-group1\">\r\n");
      out.write("								<a href=\"forgot.jsp\">Forgot password ? </a>\r\n");
      out.write("							</div>\r\n");
      out.write("							\r\n");
      out.write("							<div class=\"form-button\">\r\n");
      out.write("								<input id=\"data\" type=\"submit\"  value=\"submit\">\r\n");
      out.write("							</div>\r\n");
      out.write("							\r\n");
      out.write("							<div class=\"form-group\">\r\n");
      out.write("								<label for=\"Register\">Don't have an account ? </label>\r\n");
      out.write("								<a href=\"Register\">Register  </a>\r\n");
      out.write("							</div>\r\n");
      out.write("							\r\n");
      out.write("						</form>\r\n");
      out.write("						<!-- Below div for button  -->\r\n");
      out.write("						\r\n");
      out.write("					</section>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</main>\r\n");
      out.write("	\r\n");
      out.write("	<!-- <script type=\"text/javascript\" >\r\n");
      out.write("		$(\"form\").submit(function(e){\r\n");
      out.write("			if(!passwordCheck($(\"#password\").val(),\"#password-error\")\r\n");
      out.write("						| !emailCheck($(\"#email\").val(),\"#email-error\")){\r\n");
      out.write("				alert(\"Please fill all fields\");\r\n");
      out.write("				e.preventDefault(e);\r\n");
      out.write("			}\r\n");
      out.write("	    });\r\n");
      out.write("	\r\n");
      out.write("		$('#email').blur(function(){\r\n");
      out.write("			emailCheck($(\"#email\").val(),\"#email-error\");\r\n");
      out.write("		});\r\n");
      out.write("		$('#password').blur(function(){\r\n");
      out.write("			passwordCheck($(\"#password\").val(),\"#password-error\");\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		function emailCheck(fValue,errorField){\r\n");
      out.write("			var regex = /^([a-zA-Z0-9_\\.\\-\\+])+\\@(([a-zA-Z0-9\\-])+\\.)+([a-zA-Z0-9]{2,4})+$/;	\r\n");
      out.write("			if(nullCheck(fValue,errorField)){\r\n");
      out.write("				console.log(\"THiss not null\");\r\n");
      out.write("				if(regex.test(fValue)){\r\n");
      out.write("					$.ajax({\r\n");
      out.write("						url : \"DelUser\",\r\n");
      out.write("						type : \"post\",\r\n");
      out.write("						data : {\r\n");
      out.write("							cuEmail : fValue,\r\n");
      out.write("							isCheck : \"email\",\r\n");
      out.write("						},\r\n");
      out.write("						success : function(data) {\r\n");
      out.write("							if (data.length != 0) {\r\n");
      out.write("								$(\"#email-error\").text(\"\");\r\n");
      out.write("								return true;\r\n");
      out.write("							}\r\n");
      out.write("							else{\r\n");
      out.write("								$(\"#email-error\").text(\"Email not exist\");\r\n");
      out.write("								return false;\r\n");
      out.write("							}\r\n");
      out.write("						}\r\n");
      out.write("					});	\r\n");
      out.write("					return true;	\r\n");
      out.write("				}\r\n");
      out.write("				else{\r\n");
      out.write("					$(\"#email-error\").text(\"Please enter valid mail\");\r\n");
      out.write("					return false;\r\n");
      out.write("				}\r\n");
      out.write("				return true;\r\n");
      out.write("			}	\r\n");
      out.write("			else{\r\n");
      out.write("				return false;		\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("		function nullCheck(fValue,errorField){\r\n");
      out.write("			if(fValue.length == 0){\r\n");
      out.write("					$(errorField).text(\"Please enter field value.\");\r\n");
      out.write("					return false;\r\n");
      out.write("			}	\r\n");
      out.write("			else{\r\n");
      out.write("					$(errorField).text(\"\");\r\n");
      out.write("					return true;\r\n");
      out.write("					\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("		function passwordCheck(fValue,errorField){\r\n");
      out.write("			var regex = /^.*(?=.{8,})(?=.*\\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%&]).*$/;	\r\n");
      out.write("			if(nullCheck(fValue,errorField) && !regex.test(fValue)){\r\n");
      out.write("				$(errorField).text(\"Please enter valid password.\");\r\n");
      out.write("				return false;\r\n");
      out.write("			}	\r\n");
      out.write("			else{\r\n");
      out.write("					return true;\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("	</script>	 -->\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("	");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/views/index.jsp(11,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/resources/library/bootstrap/css/bootstrap.min.css");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /WEB-INF/views/index.jsp(12,30) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/resources/css/custom.css");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f2_reused = false;
    try {
      _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f2.setParent(null);
      // /WEB-INF/views/index.jsp(13,37) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setValue("/resources/javascript/jquery-3.6.0.min.js");
      int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
      if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      _jspx_th_c_005furl_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f2, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f2_reused);
    }
    return false;
  }
}
