/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2022-05-05 10:12:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/home/pradip/Desktop/Spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/springmvc/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1650964475785L));
    _jspx_dependants.put("jar:file:/home/pradip/Desktop/Spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/springmvc/WEB-INF/lib/jstl-1.2.jar!/META-INF/c-1_0.tld", Long.valueOf(1153365282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>Register Page</title>\r\n");
      out.write("\r\n");
      out.write("<link\r\n");
      out.write("	href='");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("'\r\n");
      out.write("	type=\"text/css\" rel=\"stylesheet\" />\r\n");
      out.write("<link rel=\"stylesheet\" href='");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("'>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("	src='");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("'></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("#imgPreview {\r\n");
      out.write("	height: 150px;\r\n");
      out.write("	width: 150px;\r\n");
      out.write("	border: 1px solid black;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<!-- Banner section -->\r\n");
      out.write("	<aside></aside>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<main>\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-md-2\"></div>\r\n");
      out.write("				<div class=\"col-md-8 col-sm-12\">\r\n");
      out.write("					<section class=\"form-section\">\r\n");
      out.write("						<form action=\"insertuser\" id=\"register-form\"\r\n");
      out.write("							enctype='multipart/form-data' method=\"post\">\r\n");
      out.write("							<!-- Below div for form heading -->\r\n");
      out.write("							<div class=\"form-heading\">\r\n");
      out.write("								<h2>Register Page</h2>\r\n");
      out.write("							</div>\r\n");
      out.write("							<input type='hidden' name='userId'>\r\n");
      out.write("\r\n");
      out.write("							<!-- Below div for name of user -->\r\n");
      out.write("							<div class=\"form-group\">\r\n");
      out.write("								<label for=\"name\">Name :</label> <input type=\"text\"\r\n");
      out.write("									class=\"form-control\" id=\"name\" name=\"name\"\r\n");
      out.write("									placeholder=\"Please enter name\">\r\n");
      out.write("								<p class=\"field-error\" id=\"name-error\"></p>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("							<!-- Below div for mobile of user -->\r\n");
      out.write("							<div class=\"form-group\">\r\n");
      out.write("								<label for=\"mobile\">Mobile :</label> <input type=\"number\"\r\n");
      out.write("									class=\"form-control\" id=\"mobile\" name=\"mobile\"\r\n");
      out.write("									placeholder=\"Please enter mobile number\">\r\n");
      out.write("								<p class=\"field-error\" id=\"mobile-error\"></p>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- Below div for email of user -->\r\n");
      out.write("							<div class=\"form-group\">\r\n");
      out.write("								<label for=\"\">Email :</label> <input type=\"text\"\r\n");
      out.write("									class=\"form-control\" id=\"email\" name=\"email\"\r\n");
      out.write("									placeholder=\"Please enter valid email\">\r\n");
      out.write("								<p class=\"field-error\" id=\"email-error\"></p>\r\n");
      out.write("\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<!-- Below div for url of user -->\r\n");
      out.write("							<div class=\"form-group\">\r\n");
      out.write("								<label for=\"date\">Birth Date :</label> <input type=\"date\"\r\n");
      out.write("									class=\"form-control\" id=\"birthdate\" name=\"birthdate\"\r\n");
      out.write("									placeholder=\"Please enter birthdate\">\r\n");
      out.write("								<p class=\"field-error\" id=\"birthdate-error\"></p>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("							<!-- Below div for gender of user -->\r\n");
      out.write("							<div class=\"form-group\">\r\n");
      out.write("								<label for=\"\">Gender :</label>\r\n");
      out.write("								<div class=\"radio\">\r\n");
      out.write("									<label> <input type=\"radio\" name=\"gender\" id=\"male\"\r\n");
      out.write("										value=\"male\"> Male\r\n");
      out.write("									</label> <label> <input type=\"radio\" name=\"gender\" id=\"female\"\r\n");
      out.write("										value=\"female\"> Female\r\n");
      out.write("									</label> <label> <input type=\"radio\" name=\"gender\" id=\"other\"\r\n");
      out.write("										value=\"other\"> other\r\n");
      out.write("									</label>\r\n");
      out.write("								</div>\r\n");
      out.write("								<p class=\"field-error\" id=\"radio-error\"></p>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- Below div for Hobby of user -->\r\n");
      out.write("							<div class=\"form-group\">\r\n");
      out.write("								<label for=\"hobby\">Hobby :</label> <select class=\"form-control\"\r\n");
      out.write("									id=\"hobby\" name=\"hobby\">\r\n");
      out.write("									<option value=\"not\">Select Hobby</option>\r\n");
      out.write("									<option value=\"Cricket\">Cricket</option>\r\n");
      out.write("									<option value=\"Travelling\">Travelling</option>\r\n");
      out.write("									<option value=\"Reading Books\">Reading Books</option>\r\n");
      out.write("									<option value=\"Learning New Things\">Learning New\r\n");
      out.write("										Things</option>\r\n");
      out.write("								</select>\r\n");
      out.write("								<p class=\"field-error\" id=\"drop-error\"></p>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"addresses\">\r\n");
      out.write("\r\n");
      out.write("								<div class=\"form-group address-section\">\r\n");
      out.write("									<label for=\"address\">Address :</label>\r\n");
      out.write("									<textarea class=\"form-control address\" rows=\"3\" class=\"address\"\r\n");
      out.write("										placeholder=\"Please enter Address\" name=\"address.general\"></textarea>\r\n");
      out.write("									<div class=\"add-style\">\r\n");
      out.write("										<span> <select class=\"form-control city\" name=\"address.city\">\r\n");
      out.write("												<option value=\"not\">Select City</option>\r\n");
      out.write("												<option value=\"botad\">Botad</option>\r\n");
      out.write("												<option value=\"ahmedabad\">Ahmedabad</option>\r\n");
      out.write("												<option value=\"baroda\">Baroda</option>\r\n");
      out.write("												<option value=\"rajkot\">Rajkot</option>\r\n");
      out.write("										</select>\r\n");
      out.write("										</span> <span> <select class=\"form-control state\" name=\"address.state\">\r\n");
      out.write("												<option value=\"not\">Select State</option>\r\n");
      out.write("												<option value=\"gujarat\">Gujarat</option>\r\n");
      out.write("												<option value=\"rajasthan\">Rajasthan</option>\r\n");
      out.write("												<option value=\"madhyapradesh\">Madhyapradesh</option>\r\n");
      out.write("										</select>\r\n");
      out.write("										</span> <span> <input type=\"number\"\r\n");
      out.write("											class=\"form-control pincode\" name=\"address.pincode\"\r\n");
      out.write("											placeholder=\"Please enter pincode\">\r\n");
      out.write("										</span> <span><a href=\"javascript:void(0);\"\r\n");
      out.write("											class=\"list_remove_button btn btn-danger\">-</a></span>\r\n");
      out.write("									</div>\r\n");
      out.write("									<input type=\"hidden\" name=\"newOldStatus\" value=\"new\">\r\n");
      out.write("									<p class=\"field-error1\"></p>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"form-group\">\r\n");
      out.write("								<p class=\"field-error\" id=\"address-max-error\"></p>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"form-button\">\r\n");
      out.write("								<button class=\"btn btn-primary list_add_button\" type=\"button\">+</button>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- Below div for password of user -->\r\n");
      out.write("							<div class=\"form-group\">\r\n");
      out.write("								<label for=\"password\">Password :</label> <input type=\"password\"\r\n");
      out.write("									name=\"password\" class=\"form-control\" id=\"password\"\r\n");
      out.write("									placeholder=\"Please enter Password\">\r\n");
      out.write("								<p class=\"field-error\" id=\"password-error\"></p>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<!-- Below div for conform password of user -->\r\n");
      out.write("							<div class=\"form-group\">\r\n");
      out.write("								<label for=\"c-password\">Confirm Password :</label> <input\r\n");
      out.write("									type=\"password\" class=\"form-control\" id=\"c-password\"\r\n");
      out.write("									name=\"cpassword\" placeholder=\"Please enter confirm Password\">\r\n");
      out.write("								<p class=\"field-error\" id=\"cpassword-error\"></p>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- Below div for image input of user -->\r\n");
      out.write("							<div class=\"form-group demo-image\">\r\n");
      out.write("								\r\n");
      out.write("								<input type=\"file\" name=\"image\" >\r\n");
      out.write("								<p class=\"field-error\" id=\"image-error\"></p>\r\n");
      out.write("								<div id=\"iii\"></div>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div class=\"form-button\">\r\n");
      out.write("								<input id=\"data\" type=\"submit\" value=\"Submit\">\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("							<div class=\"form-group\">\r\n");
      out.write("								<label for=\"\">Already have an account ? </label> <a href=\"index\">Login</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</form>\r\n");
      out.write("					</section>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("	</main>\r\n");
      out.write("\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("	<!-- Javascript file links -->\r\n");
      out.write("	<!-- 1.Already created file -->\r\n");
      out.write("\r\n");
      out.write("	<!-- 2. Custom file <script type=\"text/javascript\" src=\"assets/javascript/custom.js\"></script>-->\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.el.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.el.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.el.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/views/Register.jsp(13,7) name = value type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/resources/library/bootstrap/css/bootstrap.min.css");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.el.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.el.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.el.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /WEB-INF/views/Register.jsp(15,29) name = value type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/resources/css/custom.css");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.el.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.el.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.el.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f2_reused = false;
    try {
      _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f2.setParent(null);
      // /WEB-INF/views/Register.jsp(17,6) name = value type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setValue("/resources/javascript/jquery-3.6.0.min.js");
      int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
      if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      _jspx_th_c_005furl_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f2, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f2_reused);
    }
    return false;
  }
}
