server:
  port: 8999
  
  
spring:
  application:
    name: api-service
  cloud:
    gateway:
      routes:
        - id: address-service
          uri: lb://address-service
          predicates:
            - Path=/address/**
          filters:
            - name: CircuitBreaker
              args:
                name: address-service
                fallbackuri: forward:/AddressServiceDown
        - id: person-service
          uri: lb://person-service
          predicates:
            - Path=/person/**
          filters:
            - name: CircuitBreaker
              args:
                name: person-service
                fallbackuri: forward:/PersonServiceDown
                
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000    
  
  
  
  
  
#eureka:
#  instance:
#    hostname: localhost
   
#spring:
#  application:
#    name: api-gateway
#    
#    
#  cloud:
#    gateway:
#      routes:
#        - id: address-service
#          uri: lb://address-service
#          predicates:
#            - Path=/address/**
#      
#        - id: person-service
#          uri: lb://person-service
#          predicates:
#            - Path=/person/**
#          filters:
#          - name: CircuitBreaker
#            args: 
#             name: person-service
#             fallbackuri: forward:/PersonServiceDown
#            
#spring:
#  application:
#    name: api-gateway
#  cloud:
#    gateway:
#      routes:
#      - id: address-service
#        uri: lb://address-service
#        predicates:
#        - Path=/address/**
#        filters:
#        - name: Hystrix
#          args:
#            name: person-service
#            fallbackUri: forward:/incaseoffailureusethis  
#               
      
#        filters:
#        - name: CircuitBreaker
#          args:
#            name: address-service
#            fallbackuri: forward:/AddressServiceDown
            
            
#hystrix:
#  command:
#    fallbackmd:
#      execution:
#        isolation:
#          thread:
#            timeoutInMillieseconds: 5000
#            
#management:
#  endpoints:
#    web:
#      exposure:
#        include: hystrix.stream 
           