server:
  port: 8888



spring:
  application:
    name: api-gateway2
  cloud:
    gateway:
      routes:
        - id: person-service
          uri: lb://person-service
          predicates:
            - Path=/person/**
          filters:
            - name: CircuitBreaker
              args:
                name: person-service
                fallbackuri: forward:/PersonServiceFallback


        - id: address-service
          uri: lb://address-service
          predicates:
            - Path=/address/**
          filters:
            - name: CircuitBreaker
              args:
                name: address-service
                fallbackuri: forward:/AddressServiceFallback  

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
